In [1]:
# data cleaning

In [451]:
import pandas as pd

In [452]:
mvps = pd.read_csv("mvps.csv")
mvps.columns = map(str.lower, mvps.columns)
mvps

,unnamed: 0,rank,player,age,tm,first,pts won,pts max,share,g,...,trb,ast,stl,blk,fg%,3p%,ft%,ws,ws/48,year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,7,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
482,8,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
483,9,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
484,10,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
485,11,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

In [453]:
mvps = mvps[["player","year", "pts won", "pts max", "share"]]

In [454]:
# mvps["player"] = mvps['player'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [455]:
mvps

              player  year  pts won  pts max  share
0     Michael Jordan  1991    891.0      960  0.928
1      Magic Johnson  1991    497.0      960  0.518
2     David Robinson  1991    476.0      960  0.496
3    Charles Barkley  1991    222.0      960  0.231
4        Karl Malone  1991    142.0      960  0.148
..               ...   ...      ...      ...    ...
481    Stephen Curry  2022      4.0     1000  0.004
482       Chris Paul  2022      2.0     1000  0.002
483    DeMar DeRozan  2022      1.0     1000  0.001
484     Kevin Durant  2022      1.0     1000  0.001
485     LeBron James  2022      1.0     1000  0.001

[486 rows x 5 columns]

In [456]:
players = pd.read_csv("players.csv")
players.columns = map(str.lower, players.columns)
players

,unnamed: 0,rk,player,pos,age,tm,g,gs,mp,fg,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18912,837,601,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
18913,838,602,Trae Young,PG,23,ATL,76,76,34.9,9.4,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
18914,839,603,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
18915,840,604,Cody Zeller,C,29,POR,27,0,13.1,1.9,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
18916,841,605,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

In [457]:
# players['player'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [458]:
del players["unnamed: 0"]
del players["rk"]

In [459]:
players.head()

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [460]:
# players["player"].head(50)

In [461]:
players["player"] = players["player"].str.replace("*", "", regex = False)

In [462]:
# want each row to have one player, take greg anderson as an example

In [463]:
players.groupby(["player", "year"]).get_group(("Greg Anderson" , 1991))

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,year
8,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,2.8,.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,4.7,.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991

In [464]:
def single_row(df):
    if df.shape[0] ==1: # only one row in the group, dont do anything
        return df
    else: # otherwise we need to change
        row = df[df["tm"] == "TOT"] # we dont care about other rows, we just want row with TOT as their team
        row["tm"] = df.iloc[-1,:]["tm"] # replace the tm with the last team he played for , select last row, and select the Tm
        return row 
players = players.groupby(["player", "year"]).apply(single_row)

In [465]:
players.head(20)

                                 player pos age   tm   g  gs    mp   fg   fga  \
player        year
A.C. Green    1991 165       A.C. Green  PF  27  LAL  82  21  26.4  3.1   6.6
              1992 635       A.C. Green  PF  28  LAL  82  53  35.4  4.7   9.8
              1993 1095      A.C. Green  PF  29  LAL  82  55  34.4  4.6   8.6
              1994 1583      A.C. Green  PF  30  PHO  82  55  34.5  5.7  11.3
              1995 2072      A.C. Green  SF  31  PHO  82  52  32.8  3.8   7.5
              1996 2569      A.C. Green  SF  32  PHO  82  36  25.8  2.6   5.4
              1997 3145      A.C. Green  PF  33  DAL  83  73  30.0  2.8   5.8
              1998 3733      A.C. Green  PF  34  DAL  82  68  32.3  3.0   6.5
              1999 4292      A.C. Green  PF  35  DAL  50  35  18.5  2.2   5.1
              2000 4821      A.C. Green  PF  36  LAL  82  82  23.5  2.1   4.7
              2001 5341      A.C. Green  PF  37  MIA  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 4694   A.J. Bramlett   C  23  CLE   8   0   7.6  0.5   2.6
A.J. English  1991 128     A.J. English  SG  23  WSB  70  12  20.6  3.6   8.2
              1992 599     A.J. English  SG  24  WSB  81   6  20.6  4.5  10.4
A.J. Guyton   2001 5344     A.J. Guyton  PG  22  CHI  33   8  19.1  2.4   5.8
              2002 5898     A.J. Guyton  PG  23  CHI  45   6  13.5  2.0   5.4
              2003 6406     A.J. Guyton  PG  24  GSW   2   0   4.5  0.0   2.0
A.J. Hammons  2017 14841   A.J. Hammons   C  24  DAL  22   0   7.4  0.8   1.9
A.J. Price    2010 10747     A.J. Price  PG  23  IND  56   2  15.4  2.6   6.3
              2011 11377     A.J. Price  PG  24  IND  50   0  15.9  2.3   6.4

                           fg%  ...  orb  drb  trb  ast  stl  blk  tov   pf  \
player        year              ...
A.C. Green    1991 165    .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4
              1992 635    .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7
              1993 1095   .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8
              1994 1583   .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7
              1995 2072   .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8
              1996 2569   .484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0  1.7
              1997 3145   .483  ...  2.7  5.2  7.9  0.8  0.8  0.2  0.9  1.7
              1998 3733   .453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8  1.9
              1999 4292   .422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4  1.4
              2000 4821   .447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6  1.5
              2001 5341   .444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5  1.5
A.J. Bramlett 2000 4694   .190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4  1.6
A.J. English  1991 128    .439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6  1.8
              1992 599    .433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1  2.0
A.J. Guyton   2001 5344   .406  ...  0.3  0.8  1.1  1.9  0.3  0.2  0.7  1.1
              2002 5898   .361  ...  0.3  0.7  1.0  1.8  0.2  0.2  0.8  0.5
              2003 6406   .000  ...  0.0  0.0  0.0  1.0  0.5  0.0  0.5  0.0
A.J. Hammons  2017 14841  .405  ...  0.4  1.3  1.6  0.2  0.0  0.6  0.5  1.0
A.J. Price    2010 10747  .410  ...  0.2  1.4  1.6  1.9  0.6  0.1  1.1  0.9
              2011 11377  .356  ...  0.3  1.1  1.4  2.2  0.6  0.0  1.1  1.2

                           pts  year
player        year
A.C. Green    1991 165     9.1  1991
              1992 635    13.6  1992
              1993 1095   12.8  1993
              1994 1583   14.7  1994
              1995 2072   11.2  1995
              1996 2569    7.5  1996
              1997 3145    7.2  1997
              1998 3733    7.3  1998
              1999 4292    4.9  1999
              2000 4821    5.0  2000
              2001 5341    4.5  2001
A.J. Bramlett 2000 4694    1.0  2000
A.J. English  1991 128     8.8  1991
              1992 599    10.9  1992
A.J. Guyton   2001 5344    6.0  2001
              2002 5898    5.4  2002
              2003 6406    0.0  2003
A.J. Hammons  2017 14841   2.2  2017
A.J. Price    2010 10747   7.3  2010
              2011 11377   6.5  2011

[20 rows x 30 columns]

In [470]:
players.index = players.index.droplevel()

In [471]:
players

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,year
165,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
635,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
1095,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
1583,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
2072,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6107,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
6608,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
7190,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,1.0,1.5,2.4,0.3,0.2,0.5,0.7,2.2,3.8,2004
7791,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
8386,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [472]:
combined = players.merge(mvps, how = "outer", on = ["player", "year"])  # need to do an outer merge, need to keep all data
combined

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,ast,stl,blk,tov,pf,pts,year,pts won,pts max,share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,NaN,NaN,NaN
14693,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,NaN,NaN,NaN
14694,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,NaN,NaN,NaN
14695,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,NaN,NaN,NaN
14696,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,NaN,NaN,NaN

In [473]:
combined[combined["pts won"] > 0]

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,ast,stl,blk,tov,pf,pts,year,pts won,pts max,share
197,Al Jefferson,C,29,CHA,73,73,35.0,9.6,18.8,.509,...,2.1,0.9,1.1,1.7,2.4,21.8,2014,34.0,1250.0,0.027
346,Allen Iverson,PG,21,PHI,76,74,40.1,8.2,19.8,.416,...,7.5,2.1,0.3,4.4,3.1,23.5,1997,1.0,1150.0,0.001
348,Allen Iverson,SG,23,PHI,48,48,41.5,9.1,22.0,.412,...,4.6,2.3,0.1,3.5,2.0,26.8,1999,319.0,1180.0,0.270
349,Allen Iverson,SG,24,PHI,70,70,40.8,10.4,24.8,.421,...,4.7,2.1,0.1,3.3,2.3,28.4,2000,132.0,1210.0,0.109
350,Allen Iverson,SG,25,PHI,71,71,42.0,10.7,25.5,.420,...,4.6,2.5,0.3,3.3,2.1,31.1,2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14170,Vince Carter,SF,23,TOR,82,82,38.1,9.6,20.7,.465,...,3.9,1.3,1.1,2.2,3.2,25.7,2000,51.0,1210.0,0.042
14171,Vince Carter,SF,24,TOR,75,75,39.7,10.2,22.1,.460,...,3.9,1.5,1.1,2.2,2.7,27.6,2001,7.0,1240.0,0.006
14175,Vince Carter,SF-SG,28,NJN,77,76,36.7,9.0,20.0,.452,...,4.2,1.4,0.6,2.2,3.2,24.5,2005,3.0,1270.0,0.002
14549,Yao Ming,C,23,HOU,82,82,32.8,6.5,12.5,.522,...,1.5,0.3,1.9,2.5,3.3,17.5,2004,1.0,1230.0,0.001
14554,Yao Ming,C,28,HOU,77,77,33.6,7.4,13.4,.548,...,1.8,0.4,1.9,3.0,3.3,19.7,2009,1.0,1210.0,0.001

In [474]:
combined[["pts won", "pts max", "share"]] = combined[["pts won", "pts max", "share"]].fillna(0)

In [476]:
combined

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,ast,stl,blk,tov,pf,pts,year,pts won,pts max,share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
14693,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
14694,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0
14695,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
14696,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

## teams dataframe

In [518]:
teams = pd.read_csv("standings.csv")
teams.columns = map(str.lower,teams.columns)
teams.head(30)

,unnamed: 0,w,l,w/l%,gb,ps/g,pa/g,srs,year,team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
14,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1991,Midwest Division
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
22,8,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1991,Pacific Division
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings

In [519]:
teams = teams[~teams["w"].str.contains("Division")] # removes rows that have a string with division

In [520]:
teams["team"] = teams["team"].str.replace("*", "", regex = False) # remove asterick

In [521]:
teams.head(5)

,unnamed: 0,w,l,w/l%,gb,ps/g,pa/g,srs,year,team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets

In [522]:
teams["team"].unique() # see unique teams

array(['Boston Celtics', 'Philadelphia 76ers', 'New York Knicks',
       'Washington Bullets', 'New Jersey Nets', 'Miami Heat',
       'Chicago Bulls', 'Detroit Pistons', 'Milwaukee Bucks',
       'Atlanta Hawks', 'Indiana Pacers', 'Cleveland Cavaliers',
       'Charlotte Hornets', 'San Antonio Spurs', 'Utah Jazz',
       'Houston Rockets', 'Orlando Magic', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Denver Nuggets', 'Portland Trail Blazers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Golden State Warriors',
       'Seattle SuperSonics', 'Los Angeles Clippers', 'Sacramento Kings',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [523]:
combined["tm"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'CHI', 'GSW', 'IND',
       'WAS', 'MIN', 'BOS', 'HOU', 'DEN', 'ORL', 'NOH', 'TOR', 'SAC',
       'CHO', 'PHI', 'POR', 'DET', 'OKC', 'UTA', 'MIL', 'VAN', 'SEA',
       'NJN', 'NOK', 'LAC', 'ATL', 'CHA', 'MEM', 'NYK', 'NOP', 'BRK',
       'SAS', 'CHH'], dtype=object)

In [556]:
nicknames = {}

with open("nick.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [557]:
nicknames

{'ATL': 'Atlanta Hawks',
 'BRK': 'Brooklyn Nets',
 'BKN': 'Brooklyn Nets',
 'BOS': 'Boston Celtics',
 'CHA': 'Charlotte Bobcats',
 'CHH': 'Charlotte Hornets',
 'CHO': 'Charlotte Hornets',
 'CHI': 'Chicago Bulls',
 'CLE': 'Cleveland Cavaliers',
 'DAL': 'Dallas Mavericks',
 'DEN': 'Denver Nuggets',
 'DET': 'Detroit Pistons',
 'GSW': 'Golden State Warriors',
 'HOU': 'Houston Rockets',
 'IND': 'Indiana Pacers',
 'LAC': 'Los Angeles Clippers',
 'LAL': 'Los Angeles Lakers',
 'MEM': 'Memphis Grizzlies',
 'MIA': 'Miami Heat',
 'MIL': 'Milwaukee Bucks',
 'MIN': 'Minnesota Timberwolves',
 'NJN': 'New Jersey Nets',
 'NOH': 'New Orleans Hornets',
 'NOP': 'New Orleans Pelicans',
 'NOK': 'New Orleans/Oklahoma City Hornets',
 'NYK': 'New York Knicks',
 'OKC': 'Oklahoma City Thunder',
 'ORL': 'Orlando Magic',
 'PHI': 'Philadelphia 76ers',
 'PHX': 'Phoenix Suns',
 'PHO': 'Phoenix Suns',
 'POR': 'Portland Trail Blazers',
 'SEA': 'Seattle SuperSonics',
 'SAC': 'Sacramento Kings',
 'SAS': 'San Antonio Spurs',
 'TOR': 'Toronto Raptors',
 'UTA': 'Utah Jazz',
 'VAN': 'Vancouver Grizzlies',
 'WAS': 'Washington Wizards',
 'WSB': 'Washington Bullets'}

In [559]:
combined["team"] = combined["tm"].map(nicknames)

In [560]:
combined.head()

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,stl,blk,tov,pf,pts,year,pts won,pts max,share,team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0,Phoenix Suns

In [561]:
stats = combined.merge(teams, how = "outer", on = ["team", "year"])
stats

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,share,team,unnamed: 0,w,l,w/l%,gb,ps/g,pa/g,srs
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,Los Angeles Lakers,10,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,.484,...,0.0,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
14693,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,.286,...,0.0,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
14694,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,.470,...,0.0,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
14695,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,.459,...,0.0,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45
14696,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,.455,...,0.0,Milwaukee Bucks,7,42,40,.512,9.0,103.6,103.8,-0.45

In [563]:
del stats["unnamed: 0"]

In [567]:
# stats.dtypes # always good to check this
stats = stats.apply(pd.to_numeric, errors = "ignore")

In [568]:
stats.dtypes

player      object
pos         object
age          int64
tm          object
g            int64
gs           int64
mp         float64
fg         float64
fga        float64
fg%        float64
3p         float64
3pa        float64
3p%        float64
2p         float64
2pa        float64
2p%        float64
efg%       float64
ft         float64
fta        float64
ft%        float64
orb        float64
drb        float64
trb        float64
ast        float64
stl        float64
blk        float64
tov        float64
pf         float64
pts        float64
year         int64
pts won    float64
pts max    float64
share      float64
team        object
w            int64
l            int64
w/l%       float64
gb          object
ps/g       float64
pa/g       float64
srs        float64
dtype: object

In [572]:
stats["gb"] = stats["gb"].str.replace("—", "0")
stats["gb"].unique()

array(['5.0', '14.0', '23.0', '7.0', '0', '40.0', '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '1.0', '13.0', '17.0', '3.0', '15.0', '9.0', '2.0', '35.0',
       '20.0', '11.0', '16.0', '41.0', '12.0', '50.0', '10.0', '30.0',
       '34.0', '4.0', '1.5', '22.0', '51.0', '36.0', '43.0', '39.0',
       '18.5', '31.0', '48.0', '46.0', '10.5', '32.0', '38.0', '27.0',
       '33.0', '21.5', '45.0', '22.5', '25.5', '3.5', '20.5', '11.5',
       '44.0', '52.0', '56.0', '2.5', '12.5', '47.0', '32.5', '4.5'],
      dtype=object)

In [573]:
stats["gb"] = pd.to_numeric(stats["gb"])

In [574]:
stats.dtypes

player      object
pos         object
age          int64
tm          object
g            int64
gs           int64
mp         float64
fg         float64
fga        float64
fg%        float64
3p         float64
3pa        float64
3p%        float64
2p         float64
2pa        float64
2p%        float64
efg%       float64
ft         float64
fta        float64
ft%        float64
orb        float64
drb        float64
trb        float64
ast        float64
stl        float64
blk        float64
tov        float64
pf         float64
pts        float64
year         int64
pts won    float64
pts max    float64
share      float64
team        object
w            int64
l            int64
w/l%       float64
gb         float64
ps/g       float64
pa/g       float64
srs        float64
dtype: object

In [575]:
stats.to_csv("allstats.csv")