In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv("allstats.csv")
stats

,Unnamed: 0,player,pos,age,tm,g,gs,mp,fg,fga,...,pts max,share,team,w,l,w/l%,gb,ps/g,pa/g,srs
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,14692,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14693,14693,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14694,14694,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14695,14695,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14696,14696,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [4]:
del stats["Unnamed: 0"]

In [40]:
stats.columns

Index(['player', 'pos', 'age', 'tm', 'g', 'gs', 'mp', 'fg', 'fga', 'fg%', '3p',
       '3pa', '3p%', '2p', '2pa', '2p%', 'efg%', 'ft', 'fta', 'ft%', 'orb',
       'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'year',
       'pts won', 'pts max', 'share', 'team', 'w', 'l', 'w/l%', 'gb', 'ps/g',
       'pa/g', 'srs'],
      dtype='object')

In [82]:
predictors = [ 'age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg%', '3p',
       '3pa', '3p%', '2p', '2pa', '2p%', 'efg%', 'ft%', 'orb',
       'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts',
        'w/l%', 'gb', 'ps/g',
       'pa/g', 'srs']

In [ ]:
'''predictors = [  'g', 'gs', 'mp', 'fg', 'fga', 'fg%', '3p',
       '3pa', '3p%', '2p', '2pa', '2p%', 'efg%', 'ft', 'fta', 'ft%', 'orb',
       'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'year',
        'w', 'l', 'w/l%', 'gb', 'ps/g',
       'pa/g', 'srs']'''

In [83]:
train = stats[stats["year"] < 2022]

In [84]:
test = stats[stats["year"] == 2022]

In [85]:
from sklearn.linear_model import Ridge
# prevents overfitting and shrinks linear regression coefficients
reg = Ridge(alpha = .1) # how much coefficient is shrunk
reg.fit(train[predictors], train ["share"])

Ridge(alpha=0.1)

In [86]:
predictions = reg.predict(test[predictors])

In [87]:
predictions = pd.DataFrame(predictions, columns = ["predictions"], index = test.index)
predictions

       predictions
648       0.013128
649      -0.027969
650      -0.005601
651       0.018019
652      -0.004641
...            ...
12508    -0.015797
12509    -0.007646
12510     0.005370
12511     0.000673
12512    -0.049767

[605 rows x 1 columns]

In [88]:
combinations = pd.concat([test[["player", "share"]], predictions], axis = 1)

In [89]:
combinations

                player  share  predictions
648       Aaron Gordon    0.0     0.013128
649      Austin Rivers    0.0    -0.027969
650            Bol Bol    0.0    -0.005601
651       Bones Hyland    0.0     0.018019
652        Bryn Forbes    0.0    -0.004641
...                ...    ...          ...
12508     Micah Potter    0.0    -0.015797
12509  Rodney McGruder    0.0    -0.007646
12510        Saben Lee    0.0     0.005370
12511       Saddiq Bey    0.0     0.000673
12512   Trayvon Palmer    0.0    -0.049767

[605 rows x 3 columns]

In [90]:
combinations.sort_values("share", ascending = False).head(10)

                      player  share  predictions
663             Nikola Jokić  0.875     0.196983
837              Joel Embiid  0.706     0.192912
11678  Giannis Antetokounmpo  0.595     0.210622
907             Devin Booker  0.216     0.095180
11469            Luka Dončić  0.146     0.152153
1179            Jayson Tatum  0.043     0.098781
12226              Ja Morant  0.010     0.118918
6398           Stephen Curry  0.004     0.096287
905               Chris Paul  0.002     0.079967
8241            LeBron James  0.001     0.156648

In [91]:
# error metric

from sklearn.metrics import mean_squared_error

mean_squared_error(combinations["share"], combinations["predictions"]) # mean difference

0.0022467432154155247

In [92]:
combinations = combinations.sort_values("share", ascending = False)
combinations["rk"] = list(range(1, combinations.shape[0] + 1))

combinations

                      player  share  predictions   rk
663             Nikola Jokić  0.875     0.196983    1
837              Joel Embiid  0.706     0.192912    2
11678  Giannis Antetokounmpo  0.595     0.210622    3
907             Devin Booker  0.216     0.095180    4
11469            Luka Dončić  0.146     0.152153    5
...                      ...    ...          ...  ...
3947          Nikola Vučević  0.000     0.054256  601
3948        Patrick Williams  0.000    -0.018211  602
3949            Tony Bradley  0.000    -0.006901  603
3950        Tristan Thompson  0.000    -0.010095  604
12512         Trayvon Palmer  0.000    -0.049767  605

[605 rows x 4 columns]

In [93]:
combinations = combinations.sort_values("predictions", ascending = False)
combinations["predicted rk"] = list(range(1, combinations.shape[0] + 1))

combinations

                      player  share  predictions   rk  predicted rk
11678  Giannis Antetokounmpo  0.595     0.210622    3             1
663             Nikola Jokić  0.875     0.196983    1             2
837              Joel Embiid  0.706     0.192912    2             3
8241            LeBron James  0.001     0.156648   10             4
11469            Luka Dončić  0.146     0.152153    5             5
...                      ...    ...          ...  ...           ...
12512         Trayvon Palmer  0.000    -0.049767  605           601
12495         Derrick Walton  0.000    -0.056769  215           602
1216          Zavier Simpson  0.000    -0.060092  318           603
11821             Wes Iwundu  0.000    -0.066008  288           604
1205          Melvin Frazier  0.000    -0.122564  326           605

[605 rows x 5 columns]

In [98]:
combinations.sort_values("share", ascending = False).head(10)
combinations[combinations["predicted rk"] <= 5]

                      player  share  predictions  rk  predicted rk
11678  Giannis Antetokounmpo  0.595     0.210622   3             1
663             Nikola Jokić  0.875     0.196983   1             2
837              Joel Embiid  0.706     0.192912   2             3
8241            LeBron James  0.001     0.156648  10             4
11469            Luka Dončić  0.146     0.152153   5             5

In [95]:
def find_ap(combinations):
    actual = combinations.sort_values("share", ascending=False).head(5)
    predicted = combinations.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index,row in predicted.iterrows():
        if row["player"] in actual["player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1

    return  sum(ps) / len(ps)

In [96]:
find_ap(combinations) # this is your error metric

0.8188235294117646

In [103]:
a = pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)
a

           0     1
13  0.093472  efg%
24  0.061145  w/l%
16  0.033785   drb
15  0.022805   orb
10  0.014429    2p
19  0.012955   stl
23  0.012900   pts
20  0.011786   blk
18  0.006908   ast
5   0.005404   fga
12  0.005194   2p%
25  0.000300    gb
0   0.000275   age
1   0.000094     g
2  -0.000016    gs
26 -0.000386  ps/g
27 -0.000476  pa/g
28 -0.000736   srs
22 -0.002322    pf
3  -0.004033    mp
4  -0.005732    fg
21 -0.007494   tov
7  -0.007908    3p
8  -0.010497   3pa
9  -0.010679   3p%
14 -0.010756   ft%
11 -0.017404   2pa
17 -0.026821   trb
6  -0.159582   fg%

In [104]:
a

           0     1
13  0.093472  efg%
24  0.061145  w/l%
16  0.033785   drb
15  0.022805   orb
10  0.014429    2p
19  0.012955   stl
23  0.012900   pts
20  0.011786   blk
18  0.006908   ast
5   0.005404   fga
12  0.005194   2p%
25  0.000300    gb
0   0.000275   age
1   0.000094     g
2  -0.000016    gs
26 -0.000386  ps/g
27 -0.000476  pa/g
28 -0.000736   srs
22 -0.002322    pf
3  -0.004033    mp
4  -0.005732    fg
21 -0.007494   tov
7  -0.007908    3p
8  -0.010497   3pa
9  -0.010679   3p%
14 -0.010756   ft%
11 -0.017404   2pa
17 -0.026821   trb
6  -0.159582   fg%